### ISSUE TITLE
Validated function returning unwanted data!

### ISSUE THREAD

**Issue by shuvomohajan** [Bit-Apps-Pro/wp-validator#7]
suppose I'm giving an array 
```
[
    name => 'john'
]
```

but in validation rules, I'm validating name & age like this: 
```
[
    name: 'string',
    age: 'nullable|string'
]
```

it's giving me an array like this:
````
[
    name => 'john',
    age => null
]
````

it should not give me the age value because the request doesn't have the age key, right?

**Comment by csemazharul** [comment]
Thank you for reporting this issue. We'll work on addressing it and include the fix in our next update.
